# Source: cluster-api-aws/templates/cluster.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: d246ab8b-5fec-494a-8ffa-902522b12f45
  namespace: d246ab8b-5fec-494a-8ffa-902522b12f45
spec:
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AWSCluster
    name: d246ab8b-5fec-494a-8ffa-902522b12f45
  controlPlaneRef:
    kind: KubeadmControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    name: "d246ab8b-5fec-494a-8ffa-902522b12f45-control-plane"
