# Source: cluster-api-aws/templates/job-check.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: d246ab8b-5fec-494a-8ffa-902522b12f45-capi-aws-check
  namespace: d246ab8b-5fec-494a-8ffa-902522b12f45
spec:
  template:
    metadata:
      name: d246ab8b-5fec-494a-8ffa-902522b12f45-capi-aws
    spec:
      serviceAccountName: d246ab8b-5fec-494a-8ffa-902522b12f45-capi-aws
      containers:
      - name: wait-for-ready
        image: "ghcr.io/openinfradev/python_kubectl_argo:v1.1.0"
        imagePullPolicy: IfNotPresent
        command:
        - timeout 
        - 5m
        - /wait_for_kubeconfig.sh  
        - d246ab8b-5fec-494a-8ffa-902522b12f45
        - d246ab8b-5fec-494a-8ffa-902522b12f45
        volumeMounts:
        - name: vol
          subPath: wait_for_kubeconfig.sh
          mountPath: /wait_for_kubeconfig.sh
      volumes:
      - name: vol
        configMap:
          name: d246ab8b-5fec-494a-8ffa-902522b12f45-capi-aws
          defaultMode: 0555
      restartPolicy: OnFailure
